spring:
  application:
    name: food-log-app
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      base-url: https://api.openai.com
      chat:
        options:
          model: gpt-4o-mini
          temperature: 0.7
  datasource:
    url: jdbc:mysql://localhost:3309/food_log_app?useSSL=false&serverTimezone=UTC&characterEncoding=utf8&allowPublicKeyRetrieval=true
    username: root
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 60MB

logging:
  level:
    org.springframework.ai.chat.client.advisor: DEBUG

mybatis:
  configuration:
    map-underscore-to-camel-case: true

server:
  tomcat:
    max-http-form-post-size: -1
    max-swallow-size: 100MB

app:
  storage:
    image-dir: 'E:\\Code\\Food Log App\\food -images'

aws:
  baseUrl: https://food-log-app-images-xiaoyi.s3.us-east-2.amazonaws.com

  accessKey: ${AWS_ACCESS_KEY}
  secretKey: ${AWS_SECRET_KEY}

  s3:
    region: us-east-2
    bucket: food-log-app-images-xiaoyi
    bucketName: food-log-app-images-xiaoyi
    access-key: ${AWS_ACCESS_KEY}
    secret-key: ${AWS_SECRET_KEY}

    localRecord:
      region: us-east-2
